### PR TITLE
Allow both jpg and jpeg as possible file formats

### PR DESCRIPTION
**Pull request by firefueled**
I initially intended to simply correct the README, pointing out that the correct option is 'jpeg' and not 'jpg', but allowing both seems friendlier
I understand if y'all don't want ambiguity

### CODE REVIEW

**Comment by firefueled** [comment]
Ohh it Fixes #53

**Comment by etpinard** [comment]
Thanks for the catch!

I would prefer only accepting `jpeg` an erroring on `jpg`.

**Comment by firefueled** [comment]
Yeah, that's what I expected. No problems. I'll send an update later today.

**Comment by firefueled** [comment]
There ya go :)

**Comment by etpinard** [comment]
Thanks!

**Pull request merged**
